### ISSUE TITLE
关于客户端图标问题

### ISSUE THREAD

**Issue by soulfere** [jnrain/jnrain-android#11]
图标的磨砂效果是怎么做出来的啊？

**Comment by xen0n** [comment]
磨砂? 你需要SVG源文件么?

**Comment by xen0n** [comment]
刚看了下, 背景是实色的, 上边扣了一层半透明白到全透明白的径向渐变, 然后应该再加一层遮罩去掉球外边的高光就OK了

**Comment by xen0n** [comment]
没有follow-up，考虑到解决方案已经给出，假定问题已经解决。closing
