### ISSUE TITLE
账户管理最佳实践

### ISSUE THREAD

**Issue by xen0n** [jnrain/jnrain-android#4]
@yunxiyinzhe 本鶸花了一个多月终于跌跌撞撞用 Android 自己的账户框架实现了一部分账户认证, 也是方便年底添加新站支持... 以下是基本的说明:
- 用上了 [git-flow](https://github.com/nvie/gitflow), 账户子系统相关的提交都封在 `feature/accounts` 分支里
- 加了一个 `江南听雨 (旧站)` 账户类型, 代码都在 `org.jnrain.mobile.accounts` 包里
- 目前只改写了 `LoginActivity` 的相关接口, 注销和其他Activities根本没有接入
- 因为 KBS 用的是 cookie 认证, 所以同一时刻只能有一个账户存在, 这个条件的保障也没做

... 那么大侠能不能试着帮我接上这部分工作? 不胜感激~

**Comment by yunxiyinzhe** [comment]
我尝试着看一下吧~我android开发几乎零基础，边学边弄吧~大侠多多指教

国庆前后有估计有其他事要忙~过后工作上不忙的话,应该可以全面展开~

**Comment by yunxiyinzhe** [comment]
一直出现这个问题:Unable to execute dex: Java heap spaceJava heap space
CentOS和Win8上都这样,eclipse.ini加大也没用

**Comment by xen0n** [comment]
@yunxiyinzhe 我靠我这里编译CardsUI-Example也这样!!! 不过我可以顺利构建听雨安卓- -

**Comment by xen0n** [comment]
那... 我就先慢悠悠地做着了~ 国庆前后我也有好多听雨的工作要做呢~

**Comment by xen0n** [comment]
经过前两天的 sprint, 这个工作几乎结束了, 虽然还是有很多蛋疼的地方不过那不是我的责任, 是 KBS cookie 认证的事情, 我就先不管了... 正在分支里试最后的一些用户体验问题.
